### ISSUE TITLE
Please add support to GPT3.5

### ISSUE THREAD

**Issue by BurnsGG** [ian-kent/gptchat#9]
I already applied for the API since it was released and did not receive it yet. Seems like it's country based? so while waiting can we use GPT3.5

**Comment by pale2hall** [comment]
You can probably change this line to  `Model: openai.GPT3Dot5Turbo` 
https://github.com/ian-kent/gptchat/blob/e706e89d1eb89a5bcceab754b6337d9520834d7e/chat_loop.go#L116

and give that a try.

I'm NOT a go programmer, but from what I can tell it looks like GPTChat uses https://github.com/sashabaranov/go-openai for openai api stuff.  So you can check the docs there too.

**Note:**  You're way more likely to hit token limits tho.  GPT4 has much higher token length limits.

**Comment by NCatalani** [comment]
I've made a PR addressing this, fell free to scrutinize it. 

To try it just fork and define the environment variable **OPENAI_API_MODEL** as "_gpt-3.5-turbo_", otherwise it defaults to GPT-4.

And @pale2hall is right, you can just replace the hardcoded _**openai.GPT4**_ below with  _**openai.GPT3Dot5Turbo**_ :

https://github.com/ian-kent/gptchat/blob/e706e89d1eb89a5bcceab754b6337d9520834d7e/chat_loop.go#L116
https://github.com/ian-kent/gptchat/blob/e706e89d1eb89a5bcceab754b6337d9520834d7e/module/memory/recall.go#L19

**Comment by ian-kent** [comment]
I've merged @NCatalani's PR 🙏 

I don't think GPTChat works particularly well on GPT-3.5 though unfortunately, so hopefully you'll get a GPT-4 key soon 🤞
